debian_nfs_server/nfs-kernel-server_1%3a1.2.0-4ubuntu4.1_amd64.deb:
  size: 169618
  object_id: ba69b993-ec3f-47cf-9fb1-0fcb37212959
  sha: sha256:e3bd705d7bc4baabf04467b5ff143f5994c15db0df9fa6b6eea9067c98e66017
expat/expat-2.2.5.tar.bz2:
  size: 510868
  object_id: bb1fb7d4-894a-4418-43a4-d00f4e950f73
  sha: sha256:d9dc32efba7e74f788fcc4f212a43216fc37cf5f23f4c2339664d473353aedf6
golang/go1.9.6.linux-amd64.tar.gz:
  size: 118279574
  object_id: 497259ac-183d-48f0-63db-46617936e46a
  sha: sha256:d1eb07f99ac06906225ac2b296503f06cc257b472e7d7817b8f822fe3766ebfe
mariadb_connector_c/mariadb-connector-c-2.3.5-src.tar.gz:
  size: 540018
  object_id: 27f389e6-85e6-47c3-4c60-256dd7d9874d
  sha: sha256:2f3bf4c326d74284debf7099f30cf3615f7978d1ec22b8c1083676688a76746f
nfs-debs/keyutils_1.5.9-8ubuntu1_amd64.deb:
  size: 47054
  object_id: a7207ad8-8660-4e0d-72a1-7fdd605e131d
  sha: sha256:782865f7688ecc2a168f6c51e8e63f44326d73144a9df35087fd1e55e30d23db
nfs-debs/libevent-2.0-5_2.0.21-stable-2ubuntu0.16.04.1_amd64.deb:
  size: 114014
  object_id: 14622888-be2d-413e-4133-874bfe135968
  sha: sha256:e1acdffde386a4da7de46166ffd199771a13498f5d4fc38d61b3fa0eba305572
nfs-debs/libnfsidmap2_0.25-5_amd64.deb:
  size: 32182
  object_id: 08d519cb-e173-4652-406f-b0c23e694671
  sha: sha256:ed00ae6b3efc4c28068e5f984d8c69942c68502593da945b89b0045e7fcef396
nfs-debs/nfs-common_1%3a1.2.8-9ubuntu12.1_amd64.deb:
  size: 184334
  object_id: b6012af0-4414-4a53-7a80-8b143fe03ada
  sha: sha256:91ee605b09bd024ed97338bed442285c5980810d9a94f23aa182255e1c16316b
nfs-debs/rpcbind_0.2.3-0.2_amd64.deb:
  size: 40252
  object_id: 7f2f0cb1-6ca8-4524-44f7-30cf31a6d72e
  sha: sha256:7c9d1aca35cd01ef0c9cbc90f93e993116e84de1967c429e1130a16281fd3a6e
nginx/newrelic_nginx_agent-1.2.1.tar.gz:
  size: 5222
  object_id: c63358f6-574a-4e20-9d2b-7e1450368b6d
  sha: sha256:a5a7f9b3a7e20302943b1dd448d9b725cf3cb28d774d79f618aab7c4ddeea52b
nginx/nginx-1.13.12.tar.gz:
  size: 1016311
  object_id: e2d8ca95-56af-44c6-541d-f5bc2ccfc50b
  sha: sha256:fb92f5602cdb8d3ab1ad47dbeca151b185d62eedb67d347bbe9d79c1438c85de
nginx/nginx-dav-ext-module-0.1.0.tar.gz:
  size: 6614
  object_id: 1385f13e-3fd6-409d-4799-5852737b08f0
  sha: sha256:6b004eed8ea16ad8de4d304027bf0413cc323a95914e58625a7dc066481aae3a
nginx/nginx-upload-module-2.2-at-aba1e3f.tar.gz:
  size: 28302
  object_id: 33cedfd9-941a-406f-4780-55000e75aca6
  sha: sha256:62f3621ef7f9c0c46d01fd51e8de014319b96eb84578791cfeecd7f70995fa1e
nginx/pcre-8.42.tar.gz:
  size: 2081413
  object_id: e464286d-99cc-4dd8-74c5-daab11a68340
  sha: sha256:69acbc2fbdefb955d42a4c606dfde800c2885711d2979e356c0636efde9ec3b5
postgres/postgresql-9.6.8.tar.gz:
  size: 25580796
  object_id: 2840f9a9-8e64-4dca-59e2-dd53bb7bbc62
  sha: sha256:7a87d98cb34bbb14f10fa572730e61f75cebc438edf7af46ce4a553d994e9573
ruby-2.4/bundler-1.14.6.gem:
  size: 319488
  object_id: 23f665a6-f6c7-4107-5e4f-ccdcd0b1bded
  sha: sha256:f431206d5e89e803b7cf0dd232683eaec769ec168707e9b3d8297dba35137d40
ruby-2.4/ruby-2.4.2.tar.gz:
  size: 14187859
  object_id: 8eec75f8-97c6-4a39-6d1c-2e00c99d3c6d
  sha: sha256:93b9e75e00b262bc4def6b26b7ae8717efc252c47154abb7392e54357e6c8c9c
ruby-2.4/rubygems-2.6.14.tgz:
  size: 769418
  object_id: 3a901e7d-7e2d-4ff8-7c8b-829543b62a7e
  sha: sha256:406a45d258707f52241843e9c7902bbdcf00e7edc3e88cdb79c46659b47851ec
