expat/expat-2.5.0.tar.bz2:
  size: 569205
  object_id: 970ccd16-75ac-4c55-5280-c00c4aa8f6cc
  sha: sha256:6f0e6e01f7b30025fa05c85fdad1e5d0ec7fd35d9f61b22f34998de11969ff67
jemalloc/jemalloc-5.3.0.tar.bz2:
  size: 736023
  object_id: 1ded0db4-5ba5-4b71-58d0-3b638b98f15b
  sha: sha256:2db82d1e7119df3e71b7640219b6dfe84789bc0537983c3b7ac4f7189aecfeaa
mariadb_connector_c/mariadb-connector-c-3.3.5-src.tar.gz:
  size: 1392609
  object_id: ca059f02-93a8-491b-74cb-44dcc0a59bbc
  sha: sha256:ca72eb26f6db2befa77e48ff966f71bcd3cb44b33bd8bbb810b65e6d011c1e5c
nfs-debs/keyutils_1.5.9-8ubuntu1_amd64.deb:
  size: 47054
  object_id: a7207ad8-8660-4e0d-72a1-7fdd605e131d
  sha: sha256:782865f7688ecc2a168f6c51e8e63f44326d73144a9df35087fd1e55e30d23db
nfs-debs/keyutils_1.5.9-9.2ubuntu2_amd64.deb:
  size: 47896
  object_id: 7ec8f95e-80a7-47f5-61aa-39170aefa1f7
  sha: sha256:223a7160b6e2680d2b1f43abb067e0ccc08906bb2c5448ad4b3065f38309bbb5
nfs-debs/keyutils_1.6.1-2ubuntu3_amd64.deb:
  size: 50410
  object_id: c2faa090-48b6-435e-65f8-aa58199fc60b
  sha: sha256:39da334791f57894fa13f680470e048383074b6c02aeb58e206033c5a3d0e925
nfs-debs/libevent-2.0-5_2.0.21-stable-2ubuntu0.16.04.1_amd64.deb:
  size: 114014
  object_id: 14622888-be2d-413e-4133-874bfe135968
  sha: sha256:e1acdffde386a4da7de46166ffd199771a13498f5d4fc38d61b3fa0eba305572
nfs-debs/libevent-2.1-6_2.1.8-stable-4build1_amd64.deb:
  size: 133328
  object_id: 79b7896d-e0e9-44df-485a-82dd91b57321
  sha: sha256:76bc94b3bb4356673c61dd2a4a7b06f40de21dab051aa4b31282aa9d7798b383
nfs-debs/libevent-core-2.1-7_2.1.12-stable-1build3_amd64.deb:
  size: 93926
  object_id: e32166c6-cdd5-4adc-6b59-16eb5c9a2224
  sha: sha256:9317ae74915b9e4372f7506fbd16ae2a021e0ead79a8d88f96dad49b87d94508
nfs-debs/libnfsidmap1_2.6.1-1ubuntu1_amd64.deb:
  size: 43534
  object_id: ee3548ea-d65b-44a3-5d9e-89aedd8fbc63
  sha: sha256:3d2e81faa64aafc72d78932dc563445129c0319dc462f9af84d4724bc5836b44
nfs-debs/libnfsidmap2_0.25-5.1_amd64.deb:
  size: 27180
  object_id: b72f3c09-f9ea-48bb-45ef-fd3c3de32348
  sha: sha256:ae6eaf479efa010b313b4e0cf18812e3ca6eb50b6392b7b52e854d6acafe866b
nfs-debs/libnfsidmap2_0.25-5_amd64.deb:
  size: 32182
  object_id: 08d519cb-e173-4652-406f-b0c23e694671
  sha: sha256:ed00ae6b3efc4c28068e5f984d8c69942c68502593da945b89b0045e7fcef396
nfs-debs/nfs-common_1%3a1.2.8-9ubuntu12.1_amd64.deb:
  size: 184334
  object_id: b6012af0-4414-4a53-7a80-8b143fe03ada
  sha: sha256:91ee605b09bd024ed97338bed442285c5980810d9a94f23aa182255e1c16316b
nfs-debs/nfs-common_1.3.4-2.1ubuntu5.3_amd64.deb:
  size: 205520
  object_id: 4383380e-5ab5-4b88-7262-a02025370122
  sha: sha256:ecf4d9601d210d86d423457dd18a7d3af406ed34a273fb22ade431764fc66d67
nfs-debs/nfs-common_2.6.1-1ubuntu1_amd64.deb:
  size: 240754
  object_id: afa71390-1fab-4898-453f-01e6b71eaade
  sha: sha256:cb77f5befccc10d7dbd72cc609df378eacae2c75fd89ff4a1efaa8e5b8ca4a7e
nfs-debs/rpcbind_0.2.3-0.2_amd64.deb:
  size: 40252
  object_id: 7f2f0cb1-6ca8-4524-44f7-30cf31a6d72e
  sha: sha256:7c9d1aca35cd01ef0c9cbc90f93e993116e84de1967c429e1130a16281fd3a6e
nfs-debs/rpcbind_0.2.3-0.6ubuntu0.18.04.4_amd64.deb:
  size: 42124
  object_id: 3d7b5940-a1b8-4780-7c73-14c74163f202
  sha: sha256:ad1e5849523af0dba54a1f7e7f54d11f1a7a0131ce5de858a5ff37e61c27b35d
nfs-debs/rpcbind_1.2.6-2build1_amd64.deb:
  size: 46608
  object_id: 35c8ca5f-5593-4e77-709f-4a19657a4adc
  sha: sha256:40f5113c7d8711c2ac8ad50ffee7fa0890731e22da0a99bee3fbc6cdd1f451ac
nginx/newrelic_nginx_agent-1.2.1.tar.gz:
  size: 5222
  object_id: c63358f6-574a-4e20-9d2b-7e1450368b6d
  sha: sha256:a5a7f9b3a7e20302943b1dd448d9b725cf3cb28d774d79f618aab7c4ddeea52b
nginx/nginx-1.27.1.tar.gz:
  size: 1245244
  object_id: e7028095-e709-4222-7c3b-2eb810ec577b
  sha: sha256:bd7ba68a6ce1ea3768b771c7e2ab4955a59fb1b1ae8d554fedb6c2304104bdfc
nginx/nginx-dav-ext-module-3.0.0.tar.gz:
  size: 14558
  object_id: 44648d53-c24b-45e4-4434-007713aa5fe7
  sha: sha256:d2499d94d82d4e4eac8425d799e52883131ae86a956524040ff2fd230ef9f859
nginx/nginx-upload-module-2.3.0.tar.gz:
  size: 40139
  object_id: 2f8f59a7-8e90-4bf5-67d8-1637924ab331
  sha: sha256:c86e318addb9c88d70fdbd58ff1f6ef6f404a93070f6db8017a1f880c97946c4
nginx/pcre-8.45.tar.gz:
  size: 2096552
  object_id: a90f9f20-e23b-4755-59c7-101197325dab
  sha: sha256:4e6ce03e0336e8b4a3d6c2b70b1c5e18590a5673a98186da90d4f33c23defc09
postgres/postgresql-11.22.tar.gz:
  size: 26826810
  object_id: d1f8d34c-b438-44e7-7672-5daea8a6da66
  sha: sha256:6445a4e1533c1e8bb616d4a3784bdc4c0226b541f6f0c8d996d9f27d581d49c3
valkey/7.2.7.tar.gz:
  size: 3432758
  object_id: bff75353-8be6-461b-7da1-5e41fe3c8e3a
  sha: sha256:b3b89b1b5da82b2452e3d304213c43628654d5f15d4ea8758a48d26daa0a468e
